package com.jasonet.dash.androidtablet;
import android.content.*;import android.graphics.*;import android.net.*;import android.view.*;import java.text.*;import java.util.*;
public final class DashboardView extends View{
 private static final int BG=Color.rgb(5,15,23),CARD=Color.rgb(13,31,43),WHITE=Color.rgb(233,243,249),MUTED=Color.rgb(142,164,179),GREEN=Color.rgb(84,231,171),RED=Color.rgb(255,115,105),AMBER=Color.rgb(255,194,92);
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final SharedPreferences prefs;private final RectF[] targets=new RectF[18];private final ConnectivityManager net;private int selected,period,focus;private boolean panel,online,waiting;private long cacheTime;private float scale,ox,oy;
 private final ConnectivityManager.NetworkCallback callback=new ConnectivityManager.NetworkCallback(){@Override public void onAvailable(Network n){online=true;waiting=false;post(()->invalidate());}@Override public void onLost(Network n){online=false;waiting=false;post(()->invalidate());}};
 public DashboardView(Context c){super(c);setFocusable(true);setFocusableInTouchMode(true);prefs=c.getSharedPreferences("marketwall-tablet",0);selected=prefs.getInt("symbol",0);period=prefs.getInt("period",0);cacheTime=prefs.getLong("cache-time",0);net=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);NetworkCapabilities n=net.getNetworkCapabilities(net.getActiveNetwork());online=n!=null&&(n.hasTransport(1)||n.hasTransport(0)||n.hasTransport(3));try{net.registerDefaultNetworkCallback(callback);}catch(RuntimeException e){waiting=true;}for(int i=0;i<targets.length;i++)targets[i]=new RectF();postDelayed(()->{if(!online)waiting=true;invalidate();},1800);setContentDescription("Market Wall 平板金融看板，正在读取本地缓存");}
 @Override protected void onDetachedFromWindow(){try{net.unregisterNetworkCallback(callback);}catch(RuntimeException ignored){}super.onDetachedFromWindow();}
 private void save(){cacheTime=System.currentTimeMillis();prefs.edit().putInt("symbol",selected).putInt("period",period).putLong("cache-time",cacheTime).apply();describe();invalidate();}
 private void describe(){setContentDescription("Market Wall "+MarketData.NAMES[selected]+"，"+MarketData.PERIODS[period]+"，"+(online?"在线":"离线，显示缓存"));}
 private void text(Canvas c,String s,float x,float y,float z,int color){p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.DEFAULT);p.setTextSize(z);p.setColor(color);c.drawText(s,x,y,p);}
 private void card(Canvas c,RectF r,boolean active){p.setStyle(Paint.Style.FILL);p.setColor(active?Color.rgb(18,67,64):CARD);c.drawRoundRect(r,18,18,p);if(active){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(GREEN);c.drawRoundRect(r,18,18,p);}p.setStyle(Paint.Style.FILL);}
 @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();boolean wide=w>=h;float cw=wide?1366:768,ch=wide?768:1100;scale=Math.min(w/cw,h/ch);ox=(w-cw*scale)/2;oy=(h-ch*scale)/2;c.drawColor(Color.BLACK);c.save();c.translate(ox,oy);c.scale(scale,scale);p.setShader(new LinearGradient(0,0,cw,ch,BG,Color.rgb(3,8,13),Shader.TileMode.CLAMP));c.drawRect(0,0,cw,ch,p);p.setShader(null);text(c,"MARKET WALL",34,55,28,WHITE);text(c,wide?"全球金融看板 · 横屏":"全球金融看板 · 竖屏",34,82,17,MUTED);boolean blink=online&&System.currentTimeMillis()/700%2==0;p.setColor(online?GREEN:waiting?AMBER:RED);c.drawCircle(cw-165,43,blink?8:6,p);text(c,online?"在线":waiting?"等待网络":"已断线 · 使用缓存",cw-148,50,18,online?GREEN:waiting?AMBER:RED);String cs=cacheTime==0?"首次启动：内置数据已就绪":"缓存快照 "+new SimpleDateFormat("HH:mm",Locale.US).format(new Date(cacheTime));text(c,cs,cw-310,76,14,MUTED);if(wide)wide(c);else tall(c);c.restore();}
 private void wide(Canvas c){for(int i=0;i<4;i++){RectF r=targets[i];r.set(34+i*245,104,260+i*245,188);card(c,r,selected==i);text(c,MarketData.NAMES[i],r.left+17,r.top+29,18,WHITE);text(c,fmt(MarketData.PRICES[i]),r.left+17,r.top+58,25,WHITE);text(c,String.format(Locale.US,"%+.2f",MarketData.CHANGES[i]),r.left+17,r.top+78,16,MarketData.CHANGES[i]>=0?GREEN:RED);}RectF main=new RectF(34,210,1026,700);card(c,main,false);chart(c,main);list(c,1050,104,1325,700);text(c,"点击行情卡或列表切换标的，点击加入自选",34,738,15,MUTED);}
 private void tall(Canvas c){for(int i=0;i<4;i++){int col=i%2,row=i/2;RectF r=targets[i];r.set(24+col*365,104+row*87,355+col*365,180+row*87);card(c,r,selected==i);text(c,MarketData.NAMES[i],r.left+14,r.top+27,16,WHITE);text(c,fmt(MarketData.PRICES[i]),r.left+14,r.top+56,22,WHITE);text(c,String.format(Locale.US,"%+.2f",MarketData.CHANGES[i]),r.left+190,r.top+43,15,MarketData.CHANGES[i]>=0?GREEN:RED);}RectF main=new RectF(24,292,744,700);card(c,main,false);chart(c,main);list(c,24,726,744,1060);text(c,"触控或方向键均可操作",24,1084,15,MUTED);}
 private void chart(Canvas c,RectF b){text(c,MarketData.NAMES[selected]+" / "+MarketData.SYMBOLS[selected],b.left+20,b.top+35,19,MUTED);text(c,fmt(MarketData.PRICES[selected]),b.left+20,b.top+88,42,WHITE);double[] v=MarketData.series(selected,period);double lo=v[0],hi=v[0];for(double x:v){lo=Math.min(lo,x);hi=Math.max(hi,x);}double d=v[60]-v[0];int color=d>=0?GREEN:RED;text(c,String.format(Locale.US,"%+.2f / %+.2f%%",d,d/v[0]*100),b.right-270,b.top+48,19,color);for(int i=0;i<4;i++){RectF r=targets[i+4];r.set(b.left+20+i*78,b.top+112,b.left+82+i*78,b.top+148);card(c,r,period==i);text(c,MarketData.PERIODS[i],r.left+13,r.top+24,15,WHITE);}float left=b.left+20,right=b.right-20,top=b.top+170,bottom=b.bottom-55;p.setColor(Color.rgb(29,51,63));p.setStrokeWidth(1);for(int i=0;i<5;i++)c.drawLine(left,top+i*(bottom-top)/4,right,top+i*(bottom-top)/4,p);Path path=new Path();for(int i=0;i<v.length;i++){float x=left+i*(right-left)/60,y=(float)(bottom-.9*(v[i]-lo)/Math.max(.0001,hi-lo)*(bottom-top));if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(color);c.drawPath(path,p);p.setStyle(Paint.Style.FILL);text(c,"区间起点 "+fmt(v[0]),left,b.bottom-18,14,MUTED);text(c,"最高 "+fmt(hi),left+(right-left)/2-35,b.bottom-18,14,MUTED);text(c,"最低 "+fmt(lo),right-115,b.bottom-18,14,MUTED);RectF fav=targets[8];fav.set(b.left+20,b.bottom-48,b.left+165,b.bottom-18);card(c,fav,focus==8);text(c,"加入自选",fav.left+18,fav.top+21,14,WHITE);}
 private void list(Canvas c,float left,float top,float right,float bottom){card(c,new RectF(left,top,right,bottom),false);text(c,"热门关注 / 全部行情",left+18,top+31,18,WHITE);for(int i=0;i<9;i++){float y=top+55+i*(bottom-top-65)/9;RectF r=targets[9+i];r.set(left+12,y,right-12,y+(bottom-top-75)/9-5);card(c,r,selected==i);text(c,MarketData.SYMBOLS[i],r.left+12,r.top+22,15,WHITE);text(c,fmt(MarketData.PRICES[i]),r.right-112,r.top+22,15,MarketData.CHANGES[i]>=0?GREEN:RED);}}
 private String fmt(double x){return String.format(Locale.US,"%,.2f",x);}
 public boolean closePanel(){if(!panel)return false;panel=false;invalidate();return true;}
 private void choose(int i){if(i<4)selected=i;else if(i<8)period=i-4;else if(i==8){save();return;}else if(i<18)selected=i-9;else panel=true;save();}
 public boolean handleKey(KeyEvent e){if(e.getAction()!=KeyEvent.ACTION_DOWN)return true;int k=e.getKeyCode();if(k==KeyEvent.KEYCODE_DPAD_LEFT){focus=Math.max(0,focus-1);invalidate();return true;}if(k==KeyEvent.KEYCODE_DPAD_RIGHT){focus=Math.min(17,focus+1);invalidate();return true;}if(k==KeyEvent.KEYCODE_DPAD_UP){focus=Math.max(0,focus-4);invalidate();return true;}if(k==KeyEvent.KEYCODE_DPAD_DOWN){focus=Math.min(17,focus+4);invalidate();return true;}if(k==KeyEvent.KEYCODE_DPAD_CENTER||k==KeyEvent.KEYCODE_ENTER){choose(focus);return true;}return false;}
 @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=(e.getX()-ox)/scale,y=(e.getY()-oy)/scale;for(int i=0;i<targets.length;i++)if(targets[i].contains(x,y)){focus=i;choose(i);break;}return true;}
 @Override public boolean performClick(){super.performClick();return true;}
}
